var annotated_dup =
[
    [ "jngl", "namespacejngl.html", [
      [ "App", "classjngl_1_1App.html", "classjngl_1_1App" ],
      [ "AppParameters", "structjngl_1_1AppParameters.html", "structjngl_1_1AppParameters" ],
      [ "Color", "classjngl_1_1Color.html", "classjngl_1_1Color" ],
      [ "Container", "classjngl_1_1Container.html", "classjngl_1_1Container" ],
      [ "Controller", "classjngl_1_1Controller.html", "classjngl_1_1Controller" ],
      [ "Drawable", "classjngl_1_1Drawable.html", "classjngl_1_1Drawable" ],
      [ "Effect", "classjngl_1_1Effect.html", null ],
      [ "Executor", "classjngl_1_1Executor.html", "classjngl_1_1Executor" ],
      [ "Finally", "classjngl_1_1Finally.html", "classjngl_1_1Finally" ],
      [ "Font", "classjngl_1_1Font.html", "classjngl_1_1Font" ],
      [ "FrameBuffer", "classjngl_1_1FrameBuffer.html", "classjngl_1_1FrameBuffer" ],
      [ "ImageData", "classjngl_1_1ImageData.html", "classjngl_1_1ImageData" ],
      [ "Job", "classjngl_1_1Job.html", "classjngl_1_1Job" ],
      [ "Label", "classjngl_1_1Label.html", "classjngl_1_1Label" ],
      [ "Mat3", "classjngl_1_1Mat3.html", "classjngl_1_1Mat3" ],
      [ "Mat4", "classjngl_1_1Mat4.html", "classjngl_1_1Mat4" ],
      [ "Move", "classjngl_1_1Move.html", null ],
      [ "Pixels", "classjngl_1_1Pixels.html", null ],
      [ "ScaleablePixels", "classjngl_1_1ScaleablePixels.html", "classjngl_1_1ScaleablePixels" ],
      [ "Shader", "classjngl_1_1Shader.html", "classjngl_1_1Shader" ],
      [ "ShaderProgram", "classjngl_1_1ShaderProgram.html", "classjngl_1_1ShaderProgram" ],
      [ "Singleton", "classjngl_1_1Singleton.html", null ],
      [ "SoundFile", "classjngl_1_1SoundFile.html", "classjngl_1_1SoundFile" ],
      [ "Sprite", "classjngl_1_1Sprite.html", "classjngl_1_1Sprite" ],
      [ "Text", "classjngl_1_1Text.html", "classjngl_1_1Text" ],
      [ "TextLine", "classjngl_1_1TextLine.html", null ],
      [ "Vec2", "classjngl_1_1Vec2.html", "classjngl_1_1Vec2" ],
      [ "Vertex", "structjngl_1_1Vertex.html", "structjngl_1_1Vertex" ],
      [ "Video", "classjngl_1_1Video.html", "classjngl_1_1Video" ],
      [ "Widget", "classjngl_1_1Widget.html", "classjngl_1_1Widget" ],
      [ "Work", "classjngl_1_1Work.html", "classjngl_1_1Work" ],
      [ "Zoom", "classjngl_1_1Zoom.html", "classjngl_1_1Zoom" ]
    ] ]
];