trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- script: |
  brew install boost
  mv /usr/local/include/boost include/ios/
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Test iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
