trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- checkout: self
  submodules: true
- bash: |
    brew install boost
    ln -s /usr/local/include/boost include/ios/boost
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Test iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
