trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- bash: |
    set -x
    brew install boost tree
    mv /usr/local/include/boost include/ios/
    ls include/ios
    ls include/ios/boost
    tree include/ios
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'Test iOS'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
