var searchData=
[
  ['v_2122',['v',['../structjngl_1_1Vertex.html#a48d9522e58fa05906c6dba23e5745a72',1,'jngl::Vertex']]],
  ['va_5flist_2123',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_2124',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'valarray'],['http://en.cppreference.com/w/cpp/header/valarray.html',1,'(Global Namespace)']]],
  ['valid_2125',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value_2126',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/utility/optional/value.html',1,'std::optional::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()']]],
  ['value_5fcomp_2127',['value_comp',['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::pmr::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::pmr::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::pmr::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::pmr::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()']]],
  ['value_5fcompare_2128',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'multimap::value_compare'],['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'map::value_compare']]],
  ['value_5for_2129',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or()'],['http://en.cppreference.com/w/cpp/utility/optional/value_or.html',1,'std::optional::value_or()']]],
  ['valueless_5fby_5fexception_2130',['valueless_by_exception',['http://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',1,'std::variant']]],
  ['variant_2131',['variant',['http://en.cppreference.com/w/cpp/utility/variant.html',1,'variant'],['http://en.cppreference.com/w/cpp/header/variant.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/utility/variant/variant.html',1,'std::variant::variant()']]],
  ['variant_5falternative_2132',['variant_alternative',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5falternative_5ft_2133',['variant_alternative_t',['http://en.cppreference.com/w/cpp/utility/variant/variant_alternative.html',1,'std']]],
  ['variant_5fsize_2134',['variant_size',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['variant_5fsize_5fv_2135',['variant_size_v',['http://en.cppreference.com/w/cpp/utility/variant/variant_size.html',1,'std']]],
  ['vec2_2136',['Vec2',['../classjngl_1_1Vec2.html',1,'Vec2'],['../classjngl_1_1Vec2.html#a1ab54d75ff36ed23a47e9229039c825d',1,'jngl::Vec2::Vec2()'],['../classjngl_1_1Vec2.html#ad15f26b132fc394d0f6366484f5d8716',1,'jngl::Vec2::Vec2(double x, double y)']]],
  ['vec2_2ehpp_2137',['Vec2.hpp',['../Vec2_8hpp.html',1,'']]],
  ['vector_2138',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'vector'],['http://en.cppreference.com/w/cpp/container/vector.html',1,'vector'],['http://en.cppreference.com/w/cpp/header/vector.html',1,'(Global Namespace)'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::pmr::vector::vector()'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20char_20_3e_2139',['vector&lt; char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20line_20_3e_20_3e_2140',['vector&lt; std::shared_ptr&lt; Line &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20jngl_3a_3aeffect_20_3e_20_3e_2141',['vector&lt; std::unique_ptr&lt; jngl::Effect &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20jngl_3a_3awidget_20_3e_20_3e_2142',['vector&lt; std::unique_ptr&lt; jngl::Widget &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['version_2143',['version',['http://en.cppreference.com/w/cpp/header/version.html',1,'']]],
  ['vertex_2144',['Vertex',['../structjngl_1_1Vertex.html',1,'jngl']]],
  ['vertex_2ehpp_2145',['Vertex.hpp',['../Vertex_8hpp.html',1,'']]],
  ['vertexshader_2146',['vertexShader',['../classjngl_1_1Sprite.html#ab976556b09522328a55549bd94cdeb20',1,'jngl::Sprite']]],
  ['vfprintf_2147',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_2148',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_2149',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_2150',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['video_2151',['Video',['../classjngl_1_1Video.html',1,'Video'],['../classjngl_1_1Video.html#a8123d635017d393a24435bb9a78c99ce',1,'jngl::Video::Video()']]],
  ['video_2ehpp_2152',['Video.hpp',['../Video_8hpp.html',1,'']]],
  ['visit_2153',['visit',['http://en.cppreference.com/w/cpp/utility/variant/visit.html',1,'std']]],
  ['void_5ft_2154',['void_t',['http://en.cppreference.com/w/cpp/types/void_t.html',1,'std']]],
  ['vprintf_2155',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_2156',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_2157',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_2158',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_2159',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_2160',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_2161',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_2162',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_2163',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
