var searchData=
[
  ['rank_5fv_5153',['rank_v',['http://en.cppreference.com/w/cpp/types/rank.html',1,'std::rank_v()'],['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::rank_v()']]],
  ['ratio_5fequal_5fv_5154',['ratio_equal_v',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_equal.html',1,'std::ratio_equal_v()'],['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_equal_v()']]],
  ['ratio_5fgreater_5fequal_5fv_5155',['ratio_greater_equal_v',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_greater_equal.html',1,'std::ratio_greater_equal_v()'],['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_greater_equal_v()']]],
  ['ratio_5fgreater_5fv_5156',['ratio_greater_v',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_greater.html',1,'std::ratio_greater_v()'],['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_greater_v()']]],
  ['ratio_5fless_5fequal_5fv_5157',['ratio_less_equal_v',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_less_equal.html',1,'std::ratio_less_equal_v()'],['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_less_equal_v()']]],
  ['ratio_5fless_5fv_5158',['ratio_less_v',['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_less_v()'],['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_less.html',1,'std::ratio_less_v()']]],
  ['ratio_5fnot_5fequal_5fv_5159',['ratio_not_equal_v',['http://en.cppreference.com/w/cpp/experimental/type_trait_variable_templates.html',1,'std::experimental::ratio_not_equal_v()'],['http://en.cppreference.com/w/cpp/numeric/ratio/ratio_not_equal.html',1,'std::ratio_not_equal_v()']]],
  ['rem_5160',['rem',['http://en.cppreference.com/w/cpp/numeric/math/div.html',1,'std::lldiv_t::rem()'],['http://en.cppreference.com/w/cpp/numeric/math/div.html',1,'std::ldiv_t::rem()'],['http://en.cppreference.com/w/cpp/numeric/math/div.html',1,'std::imaxdiv_t::rem()'],['http://en.cppreference.com/w/cpp/numeric/math/div.html',1,'std::div_t::rem()']]]
];
