env = Environment()
debug = ARGUMENTS.get('debug', 0)
if int(debug):
	env.Append(CCFLAGS = '-g -Wall')
else:
	env.Append(CCFLAGS = '-O2')
env.ParseConfig("pkg-config jngl --cflags --libs")
env.Program(target="bike", source=Split("main.cpp bike.cpp vector2d.cpp wheel.cpp line.cpp base.cpp"))
