env = Environment()
debug = ARGUMENTS.get('debug', 0)
if int(debug):
	env.Append(CCFLAGS = '-g -Wall')
else:
	env.Append(CCFLAGS = '-O2')

files = Split("main.cpp bike.cpp vector2d.cpp wheel.cpp line.cpp base.cpp")

if env['PLATFORM'] == 'posix': # Linux
	env.ParseConfig("pkg-config jngl --cflags --libs")
	env.Program(target="bike", source=files)

if env['PLATFORM'] == 'win32': # Windows
	linkflags = "-mwindows"
	if int(debug):
		linkflags = ""
	env.Program(files, CPPPATH="../..", LIBPATH="../..", LIBS=Split("jngl freetype png opengl32 glu32 user32 shell32 gdi32 z jpeg"), LINKFLAGS=linkflags)
