#!/usr/bin/env python3
# Copyright 2026 Jan Niklas Hasse <jhasse@bixense.com>
# For conditions of distribution and use, see copyright notice in LICENSE.txt
"""Embeds a SPIR-V binary as a constexpr std::array<uint32_t> in a C++ header."""

import struct
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <input.spv> <output.hpp> <symbol_name>", file=sys.stderr)
        return 1

    spirv_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    symbol_name = sys.argv[3]

    data = spirv_path.read_bytes()
    if len(data) % 4 != 0:
        print(f"{spirv_path}: SPIR-V size is not a multiple of 4", file=sys.stderr)
        return 1

    words = struct.unpack(f"<{len(data) // 4}I", data)
    words_per_line = 6
    lines = []
    for i in range(0, len(words), words_per_line):
        chunk = words[i : i + words_per_line]
        lines.append("\t" + ", ".join(f"0x{word:08x}u" for word in chunk) + ",")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "// Generated by cmake/spirv_to_header.py; do not edit.\n"
        "#pragma once\n\n"
        "#include <array>\n"
        "#include <cstdint>\n\n"
        "namespace jngl::vulkan_shaders {\n\n"
        f"inline constexpr std::array<uint32_t, {len(words)}> {symbol_name} = {{\n"
        + "\n".join(lines)
        + "\n};\n\n"
        "} // namespace jngl::vulkan_shaders\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
