name: GitHub Pages
on:
  push:
jobs:
  doxygen:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
         sudo apt update
         sudo apt install graphviz doxygen cmake
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build
        run: |
          cmake .
          make
          doxygen
          sed -i 'sx<div class="title">Documentation </div>xxg' html/index.html # Remove header from index.html only
        working-directory: doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/html
