name: GitHub Pages
on:
  push:
jobs:
  doxygen:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora-minimal:40
    steps:
      - name: Install dependencies
        run: microdnf install -y git graphviz doxygen cmake make tar xz rsync
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        run: |
          cmake .
          make
          doxygen
        working-directory: doc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/html
